# Generated by Django 3.2.4 on 2021-06-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
